# Use root/example as user/password credentials
version: '3.3'

services:
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "estrella_marina"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    ports:
      - '5330:5330'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=5330
      - PMA_HOSTS=database_mysql_1
    ports:
      - 5454:80